services:
  postgres:
    image: postgres:16
    container_name: distqueue-postgres
    environment:
      POSTGRES_USER: distqueue
      POSTGRES_PASSWORD: distqueue
      POSTGRES_DB: distqueue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: distqueue-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
